services:
  
  db:
    image: postgres
    container_name: ${PG_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tg_bot
      # - userbot
    env_file:
      - .env

  redis_cache:
    image: redis:6.2-alpine
    container_name: redis_cache
    restart: always
    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./cache:/data
    ports:
      - "6379:6379"
    env_file:
      - .env
  
  tg_bot:
    build: .
    container_name: assistbot
    restart: always
    volumes:
      - .:/app
    working_dir: /app/assistBot
    command: python main.py
    env_file:
      - .env
    depends_on:
      - db
      - redis_cache
    environment:
      REDIS_URL: redis://redis_cache:6379/0
    networks:
      - tg_bot
  
  userbot:
    build: .
    container_name: userbot
    restart: always
    volumes:
      - .:/app
    depends_on:
      - tg_bot
      - db
    working_dir: /app
    command: python -m userbot.main
    environment:
      - PYTHONPATH=/app
    networks:
      - tg_bot
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - tg_bot

networks:
  tg_bot: {}
  userbot: {}

volumes:
  pgdata: {}